services:
  telegram_chess_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  redis:
    image: redis
    ports:
      - 26379:26379

networks:
  default:
    name: bridge-nerwork
    external: true
